version: '3'

services:

  ezops-app:
    image: node:14
    working_dir: /app
    command: ['npm','run','server']
    volumes: 
      - ./:/app
    ports:
      - 3000:3000
    environment:
      APP_PORT: 3000
      DB_STR_CONNECTION: "mongodb://root:dev@ezops-db:27017"
  
  ezops-db:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
      