name: ci

on:
  push:
    branches:
      - "master"

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/build-push-action@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: farpado/ezops-chat-app:latest
          build-args: |
            APP_PORT=3000
            DB_STR_CONNECTION=${{ secrets.DB_STR_CONNECTION }}
  continuous-deployment:
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    steps:
    - name: Deploy to my EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_NAME }}
        username: "ubuntu"
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          sudo docker pull farpado/ezops-chat-app:latest
          sudo docker rm -f ezops-chat-app
          sudo docker run -d --name=chat-app -p 3000:3000 --restart=always farpado/ezops-chat-app:latest
